name    'fiddyspence-pe_apacheha'
version '0.0.1'
source 'UNKNOWN'
author 'fiddyspence'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
dependency 'puppetlabs/apache', '>= 0.4.0'
dependency 'fiddyspence/sysctl', '>= 0.0.1'
